name: automerge
on:
  workflow_dispatch:
  schedule:
    - cron: '42 2,5,8,11 * * *'

jobs:
  automerge:
    uses: llmzy/github-workflows/.github/workflows/automerge.yml@main
    with:
      registryUrl: 'https://npm.pkg.github.com'
      scope: '@llmzy'
    secrets: inherit
